/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pozicio from './Pozicio';
import Status from './Status';

/**
 * The Jatekos model module.
 * @module model/Jatekos
 * @version v1.2
 */
class Jatekos {
    /**
     * Constructs a new <code>Jatekos</code>.
     * @alias module:model/Jatekos
     */
    constructor() { 
        
        Jatekos.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Jatekos</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Jatekos} obj Optional instance to populate.
     * @return {module:model/Jatekos} The populated <code>Jatekos</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Jatekos();

            if (data.hasOwnProperty('jatekosId')) {
                obj['jatekosId'] = ApiClient.convertToType(data['jatekosId'], 'Number');
            }
            if (data.hasOwnProperty('vezeteknev')) {
                obj['vezeteknev'] = ApiClient.convertToType(data['vezeteknev'], 'String');
            }
            if (data.hasOwnProperty('keresztnev')) {
                obj['keresztnev'] = ApiClient.convertToType(data['keresztnev'], 'String');
            }
            if (data.hasOwnProperty('szuletesiDatum')) {
                obj['szuletesiDatum'] = ApiClient.convertToType(data['szuletesiDatum'], 'Date');
            }
            if (data.hasOwnProperty('nemzetisegId')) {
                obj['nemzetisegId'] = ApiClient.convertToType(data['nemzetisegId'], 'Number');
            }
            if (data.hasOwnProperty('pozicio')) {
                obj['pozicio'] = Pozicio.constructFromObject(data['pozicio']);
            }
            if (data.hasOwnProperty('csapatId')) {
                obj['csapatId'] = ApiClient.convertToType(data['csapatId'], 'Number');
            }
            if (data.hasOwnProperty('statuszId')) {
                obj['statuszId'] = Status.constructFromObject(data['statuszId']);
            }
            if (data.hasOwnProperty('media_Id')) {
                obj['media_Id'] = ApiClient.convertToType(data['media_Id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Jatekos</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Jatekos</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['vezeteknev'] && !(typeof data['vezeteknev'] === 'string' || data['vezeteknev'] instanceof String)) {
            throw new Error("Expected the field `vezeteknev` to be a primitive type in the JSON string but got " + data['vezeteknev']);
        }
        // ensure the json data is a string
        if (data['keresztnev'] && !(typeof data['keresztnev'] === 'string' || data['keresztnev'] instanceof String)) {
            throw new Error("Expected the field `keresztnev` to be a primitive type in the JSON string but got " + data['keresztnev']);
        }

        return true;
    }


}



/**
 * @member {Number} jatekosId
 */
Jatekos.prototype['jatekosId'] = undefined;

/**
 * @member {String} vezeteknev
 */
Jatekos.prototype['vezeteknev'] = undefined;

/**
 * @member {String} keresztnev
 */
Jatekos.prototype['keresztnev'] = undefined;

/**
 * @member {Date} szuletesiDatum
 */
Jatekos.prototype['szuletesiDatum'] = undefined;

/**
 * @member {Number} nemzetisegId
 */
Jatekos.prototype['nemzetisegId'] = undefined;

/**
 * @member {module:model/Pozicio} pozicio
 */
Jatekos.prototype['pozicio'] = undefined;

/**
 * @member {Number} csapatId
 */
Jatekos.prototype['csapatId'] = undefined;

/**
 * @member {module:model/Status} statuszId
 */
Jatekos.prototype['statuszId'] = undefined;

/**
 * @member {Number} media_Id
 */
Jatekos.prototype['media_Id'] = undefined;






export default Jatekos;

