/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerkozesTipus from './MerkozesTipus';

/**
 * The Merkozes model module.
 * @module model/Merkozes
 * @version v1.2
 */
class Merkozes {
    /**
     * Constructs a new <code>Merkozes</code>.
     * @alias module:model/Merkozes
     */
    constructor() { 
        
        Merkozes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Merkozes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Merkozes} obj Optional instance to populate.
     * @return {module:model/Merkozes} The populated <code>Merkozes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Merkozes();

            if (data.hasOwnProperty('merkozesId')) {
                obj['merkozesId'] = ApiClient.convertToType(data['merkozesId'], 'Number');
            }
            if (data.hasOwnProperty('merkozesDatum')) {
                obj['merkozesDatum'] = ApiClient.convertToType(data['merkozesDatum'], 'Date');
            }
            if (data.hasOwnProperty('hazaiCsapatId')) {
                obj['hazaiCsapatId'] = ApiClient.convertToType(data['hazaiCsapatId'], 'Number');
            }
            if (data.hasOwnProperty('vendegCsapatId')) {
                obj['vendegCsapatId'] = ApiClient.convertToType(data['vendegCsapatId'], 'Number');
            }
            if (data.hasOwnProperty('merkozesTipus')) {
                obj['merkozesTipus'] = MerkozesTipus.constructFromObject(data['merkozesTipus']);
            }
            if (data.hasOwnProperty('ev')) {
                obj['ev'] = ApiClient.convertToType(data['ev'], 'Number');
            }
            if (data.hasOwnProperty('szervezo')) {
                obj['szervezo'] = ApiClient.convertToType(data['szervezo'], 'String');
            }
            if (data.hasOwnProperty('versenyId')) {
                obj['versenyId'] = ApiClient.convertToType(data['versenyId'], 'Number');
            }
            if (data.hasOwnProperty('stadionId')) {
                obj['stadionId'] = ApiClient.convertToType(data['stadionId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Merkozes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Merkozes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['szervezo'] && !(typeof data['szervezo'] === 'string' || data['szervezo'] instanceof String)) {
            throw new Error("Expected the field `szervezo` to be a primitive type in the JSON string but got " + data['szervezo']);
        }

        return true;
    }


}



/**
 * @member {Number} merkozesId
 */
Merkozes.prototype['merkozesId'] = undefined;

/**
 * @member {Date} merkozesDatum
 */
Merkozes.prototype['merkozesDatum'] = undefined;

/**
 * @member {Number} hazaiCsapatId
 */
Merkozes.prototype['hazaiCsapatId'] = undefined;

/**
 * @member {Number} vendegCsapatId
 */
Merkozes.prototype['vendegCsapatId'] = undefined;

/**
 * @member {module:model/MerkozesTipus} merkozesTipus
 */
Merkozes.prototype['merkozesTipus'] = undefined;

/**
 * @member {Number} ev
 */
Merkozes.prototype['ev'] = undefined;

/**
 * @member {String} szervezo
 */
Merkozes.prototype['szervezo'] = undefined;

/**
 * @member {Number} versenyId
 */
Merkozes.prototype['versenyId'] = undefined;

/**
 * @member {Number} stadionId
 */
Merkozes.prototype['stadionId'] = undefined;






export default Merkozes;

