/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Stadion model module.
 * @module model/Stadion
 * @version v1.2
 */
class Stadion {
    /**
     * Constructs a new <code>Stadion</code>.
     * @alias module:model/Stadion
     * @param stadionNeve {String} 
     */
    constructor(stadionNeve) { 
        
        Stadion.initialize(this, stadionNeve);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, stadionNeve) { 
        obj['stadionNeve'] = stadionNeve;
    }

    /**
     * Constructs a <code>Stadion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Stadion} obj Optional instance to populate.
     * @return {module:model/Stadion} The populated <code>Stadion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Stadion();

            if (data.hasOwnProperty('stadionId')) {
                obj['stadionId'] = ApiClient.convertToType(data['stadionId'], 'Number');
            }
            if (data.hasOwnProperty('stadionNeve')) {
                obj['stadionNeve'] = ApiClient.convertToType(data['stadionNeve'], 'String');
            }
            if (data.hasOwnProperty('varosId')) {
                obj['varosId'] = ApiClient.convertToType(data['varosId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Stadion</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Stadion</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Stadion.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['stadionNeve'] && !(typeof data['stadionNeve'] === 'string' || data['stadionNeve'] instanceof String)) {
            throw new Error("Expected the field `stadionNeve` to be a primitive type in the JSON string but got " + data['stadionNeve']);
        }

        return true;
    }


}

Stadion.RequiredProperties = ["stadionNeve"];

/**
 * @member {Number} stadionId
 */
Stadion.prototype['stadionId'] = undefined;

/**
 * @member {String} stadionNeve
 */
Stadion.prototype['stadionNeve'] = undefined;

/**
 * @member {Number} varosId
 */
Stadion.prototype['varosId'] = undefined;






export default Stadion;

