/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SzankcioTipus from './SzankcioTipus';

/**
 * The Szankcio model module.
 * @module model/Szankcio
 * @version v1.2
 */
class Szankcio {
    /**
     * Constructs a new <code>Szankcio</code>.
     * @alias module:model/Szankcio
     */
    constructor() { 
        
        Szankcio.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Szankcio</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Szankcio} obj Optional instance to populate.
     * @return {module:model/Szankcio} The populated <code>Szankcio</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Szankcio();

            if (data.hasOwnProperty('szankcioId')) {
                obj['szankcioId'] = ApiClient.convertToType(data['szankcioId'], 'Number');
            }
            if (data.hasOwnProperty('jatekosId')) {
                obj['jatekosId'] = ApiClient.convertToType(data['jatekosId'], 'Number');
            }
            if (data.hasOwnProperty('merkozesId')) {
                obj['merkozesId'] = ApiClient.convertToType(data['merkozesId'], 'Number');
            }
            if (data.hasOwnProperty('szankcioTipus')) {
                obj['szankcioTipus'] = SzankcioTipus.constructFromObject(data['szankcioTipus']);
            }
            if (data.hasOwnProperty('szankcioIdeje')) {
                obj['szankcioIdeje'] = ApiClient.convertToType(data['szankcioIdeje'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Szankcio</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Szankcio</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} szankcioId
 */
Szankcio.prototype['szankcioId'] = undefined;

/**
 * @member {Number} jatekosId
 */
Szankcio.prototype['jatekosId'] = undefined;

/**
 * @member {Number} merkozesId
 */
Szankcio.prototype['merkozesId'] = undefined;

/**
 * @member {module:model/SzankcioTipus} szankcioTipus
 */
Szankcio.prototype['szankcioTipus'] = undefined;

/**
 * @member {Date} szankcioIdeje
 */
Szankcio.prototype['szankcioIdeje'] = undefined;






export default Szankcio;

