/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Varos model module.
 * @module model/Varos
 * @version v1.2
 */
class Varos {
    /**
     * Constructs a new <code>Varos</code>.
     * @alias module:model/Varos
     * @param varosNev {String} 
     */
    constructor(varosNev) { 
        
        Varos.initialize(this, varosNev);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, varosNev) { 
        obj['varosNev'] = varosNev;
    }

    /**
     * Constructs a <code>Varos</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Varos} obj Optional instance to populate.
     * @return {module:model/Varos} The populated <code>Varos</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Varos();

            if (data.hasOwnProperty('varosId')) {
                obj['varosId'] = ApiClient.convertToType(data['varosId'], 'Number');
            }
            if (data.hasOwnProperty('varosNev')) {
                obj['varosNev'] = ApiClient.convertToType(data['varosNev'], 'String');
            }
            if (data.hasOwnProperty('nemzetisegId')) {
                obj['nemzetisegId'] = ApiClient.convertToType(data['nemzetisegId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Varos</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Varos</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Varos.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['varosNev'] && !(typeof data['varosNev'] === 'string' || data['varosNev'] instanceof String)) {
            throw new Error("Expected the field `varosNev` to be a primitive type in the JSON string but got " + data['varosNev']);
        }

        return true;
    }


}

Varos.RequiredProperties = ["varosNev"];

/**
 * @member {Number} varosId
 */
Varos.prototype['varosId'] = undefined;

/**
 * @member {String} varosNev
 */
Varos.prototype['varosNev'] = undefined;

/**
 * @member {Number} nemzetisegId
 */
Varos.prototype['nemzetisegId'] = undefined;






export default Varos;

