/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Verseny model module.
 * @module model/Verseny
 * @version v1.2
 */
class Verseny {
    /**
     * Constructs a new <code>Verseny</code>.
     * @alias module:model/Verseny
     */
    constructor() { 
        
        Verseny.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Verseny</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Verseny} obj Optional instance to populate.
     * @return {module:model/Verseny} The populated <code>Verseny</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Verseny();

            if (data.hasOwnProperty('versenyId')) {
                obj['versenyId'] = ApiClient.convertToType(data['versenyId'], 'Number');
            }
            if (data.hasOwnProperty('liga')) {
                obj['liga'] = ApiClient.convertToType(data['liga'], 'String');
            }
            if (data.hasOwnProperty('fordulo')) {
                obj['fordulo'] = ApiClient.convertToType(data['fordulo'], 'Number');
            }
            if (data.hasOwnProperty('stadionId')) {
                obj['stadionId'] = ApiClient.convertToType(data['stadionId'], 'Number');
            }
            if (data.hasOwnProperty('kezdesDatum')) {
                obj['kezdesDatum'] = ApiClient.convertToType(data['kezdesDatum'], 'Date');
            }
            if (data.hasOwnProperty('befejezesDatum')) {
                obj['befejezesDatum'] = ApiClient.convertToType(data['befejezesDatum'], 'Date');
            }
            if (data.hasOwnProperty('leiras')) {
                obj['leiras'] = ApiClient.convertToType(data['leiras'], 'String');
            }
            if (data.hasOwnProperty('aktualis')) {
                obj['aktualis'] = ApiClient.convertToType(data['aktualis'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Verseny</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Verseny</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['liga'] && !(typeof data['liga'] === 'string' || data['liga'] instanceof String)) {
            throw new Error("Expected the field `liga` to be a primitive type in the JSON string but got " + data['liga']);
        }
        // ensure the json data is a string
        if (data['leiras'] && !(typeof data['leiras'] === 'string' || data['leiras'] instanceof String)) {
            throw new Error("Expected the field `leiras` to be a primitive type in the JSON string but got " + data['leiras']);
        }

        return true;
    }


}



/**
 * @member {Number} versenyId
 */
Verseny.prototype['versenyId'] = undefined;

/**
 * @member {String} liga
 */
Verseny.prototype['liga'] = undefined;

/**
 * @member {Number} fordulo
 */
Verseny.prototype['fordulo'] = undefined;

/**
 * @member {Number} stadionId
 */
Verseny.prototype['stadionId'] = undefined;

/**
 * @member {Date} kezdesDatum
 */
Verseny.prototype['kezdesDatum'] = undefined;

/**
 * @member {Date} befejezesDatum
 */
Verseny.prototype['befejezesDatum'] = undefined;

/**
 * @member {String} leiras
 */
Verseny.prototype['leiras'] = undefined;

/**
 * @member {Boolean} aktualis
 */
Verseny.prototype['aktualis'] = undefined;






export default Verseny;

