/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MlszApi);
  }
}(this, function(expect, MlszApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MlszApi.CsapatApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CsapatApi', function() {
    describe('apiCsapatGet', function() {
      it('should call apiCsapatGet successfully', function(done) {
        //uncomment below and update the code to test apiCsapatGet
        //instance.apiCsapatGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiCsapatIdDelete', function() {
      it('should call apiCsapatIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiCsapatIdDelete
        //instance.apiCsapatIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiCsapatIdGet', function() {
      it('should call apiCsapatIdGet successfully', function(done) {
        //uncomment below and update the code to test apiCsapatIdGet
        //instance.apiCsapatIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiCsapatIdPut', function() {
      it('should call apiCsapatIdPut successfully', function(done) {
        //uncomment below and update the code to test apiCsapatIdPut
        //instance.apiCsapatIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiCsapatPost', function() {
      it('should call apiCsapatPost successfully', function(done) {
        //uncomment below and update the code to test apiCsapatPost
        //instance.apiCsapatPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
