/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MlszApi);
  }
}(this, function(expect, MlszApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MlszApi.JatekosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JatekosApi', function() {
    describe('jatekosGet', function() {
      it('should call jatekosGet successfully', function(done) {
        //uncomment below and update the code to test jatekosGet
        //instance.jatekosGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jatekosIdAsszisztgolokGet', function() {
      it('should call jatekosIdAsszisztgolokGet successfully', function(done) {
        //uncomment below and update the code to test jatekosIdAsszisztgolokGet
        //instance.jatekosIdAsszisztgolokGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jatekosIdDelete', function() {
      it('should call jatekosIdDelete successfully', function(done) {
        //uncomment below and update the code to test jatekosIdDelete
        //instance.jatekosIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jatekosIdGet', function() {
      it('should call jatekosIdGet successfully', function(done) {
        //uncomment below and update the code to test jatekosIdGet
        //instance.jatekosIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jatekosIdGolokGet', function() {
      it('should call jatekosIdGolokGet successfully', function(done) {
        //uncomment below and update the code to test jatekosIdGolokGet
        //instance.jatekosIdGolokGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jatekosIdPut', function() {
      it('should call jatekosIdPut successfully', function(done) {
        //uncomment below and update the code to test jatekosIdPut
        //instance.jatekosIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jatekosIdSzankciokGet', function() {
      it('should call jatekosIdSzankciokGet successfully', function(done) {
        //uncomment below and update the code to test jatekosIdSzankciokGet
        //instance.jatekosIdSzankciokGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jatekosPost', function() {
      it('should call jatekosPost successfully', function(done) {
        //uncomment below and update the code to test jatekosPost
        //instance.jatekosPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
