/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MlszApi);
  }
}(this, function(expect, MlszApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MlszApi.NemzetisegApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NemzetisegApi', function() {
    describe('nemzetisegGet', function() {
      it('should call nemzetisegGet successfully', function(done) {
        //uncomment below and update the code to test nemzetisegGet
        //instance.nemzetisegGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nemzetisegIdDelete', function() {
      it('should call nemzetisegIdDelete successfully', function(done) {
        //uncomment below and update the code to test nemzetisegIdDelete
        //instance.nemzetisegIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nemzetisegIdGet', function() {
      it('should call nemzetisegIdGet successfully', function(done) {
        //uncomment below and update the code to test nemzetisegIdGet
        //instance.nemzetisegIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nemzetisegIdPut', function() {
      it('should call nemzetisegIdPut successfully', function(done) {
        //uncomment below and update the code to test nemzetisegIdPut
        //instance.nemzetisegIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nemzetisegPost', function() {
      it('should call nemzetisegPost successfully', function(done) {
        //uncomment below and update the code to test nemzetisegPost
        //instance.nemzetisegPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
