/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Csapat from '../model/Csapat';

/**
* Csapat service.
* @module api/CsapatApi
* @version v1.2
*/
export default class CsapatApi {

    /**
    * Constructs a new CsapatApi. 
    * @alias module:api/CsapatApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiCsapatGet operation.
     * @callback module:api/CsapatApi~apiCsapatGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Csapat>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/CsapatApi~apiCsapatGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Csapat>}
     */
    apiCsapatGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [Csapat];
      return this.apiClient.callApi(
        '/api/Csapat', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiCsapatIdDelete operation.
     * @callback module:api/CsapatApi~apiCsapatIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/CsapatApi~apiCsapatIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiCsapatIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiCsapatIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/Csapat/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiCsapatIdGet operation.
     * @callback module:api/CsapatApi~apiCsapatIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Csapat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/CsapatApi~apiCsapatIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Csapat}
     */
    apiCsapatIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiCsapatIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = Csapat;
      return this.apiClient.callApi(
        '/api/Csapat/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiCsapatIdPut operation.
     * @callback module:api/CsapatApi~apiCsapatIdPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/Csapat} [csapat] 
     * @param {module:api/CsapatApi~apiCsapatIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiCsapatIdPut(id, opts, callback) {
      opts = opts || {};
      let postBody = opts['csapat'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiCsapatIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/Csapat/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiCsapatPost operation.
     * @callback module:api/CsapatApi~apiCsapatPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Csapat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/Csapat} [csapat] 
     * @param {module:api/CsapatApi~apiCsapatPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Csapat}
     */
    apiCsapatPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['csapat'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = Csapat;
      return this.apiClient.callApi(
        '/api/Csapat', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
