/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Gol from '../model/Gol';
import Jatekos from '../model/Jatekos';
import Szankcio from '../model/Szankcio';

/**
* Jatekos service.
* @module api/JatekosApi
* @version v1.2
*/
export default class JatekosApi {

    /**
    * Constructs a new JatekosApi. 
    * @alias module:api/JatekosApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the jatekosGet operation.
     * @callback module:api/JatekosApi~jatekosGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Jatekos>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/JatekosApi~jatekosGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Jatekos>}
     */
    jatekosGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [Jatekos];
      return this.apiClient.callApi(
        '/Jatekos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the jatekosIdAsszisztgolokGet operation.
     * @callback module:api/JatekosApi~jatekosIdAsszisztgolokGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Gol>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/JatekosApi~jatekosIdAsszisztgolokGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Gol>}
     */
    jatekosIdAsszisztgolokGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling jatekosIdAsszisztgolokGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [Gol];
      return this.apiClient.callApi(
        '/Jatekos/{id}/asszisztgolok', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the jatekosIdDelete operation.
     * @callback module:api/JatekosApi~jatekosIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/JatekosApi~jatekosIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    jatekosIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling jatekosIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/Jatekos/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the jatekosIdGet operation.
     * @callback module:api/JatekosApi~jatekosIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Jatekos} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/JatekosApi~jatekosIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Jatekos}
     */
    jatekosIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling jatekosIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = Jatekos;
      return this.apiClient.callApi(
        '/Jatekos/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the jatekosIdGolokGet operation.
     * @callback module:api/JatekosApi~jatekosIdGolokGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Gol>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/JatekosApi~jatekosIdGolokGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Gol>}
     */
    jatekosIdGolokGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling jatekosIdGolokGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [Gol];
      return this.apiClient.callApi(
        '/Jatekos/{id}/golok', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the jatekosIdPut operation.
     * @callback module:api/JatekosApi~jatekosIdPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/Jatekos} [jatekos] 
     * @param {module:api/JatekosApi~jatekosIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    jatekosIdPut(id, opts, callback) {
      opts = opts || {};
      let postBody = opts['jatekos'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling jatekosIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/Jatekos/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the jatekosIdSzankciokGet operation.
     * @callback module:api/JatekosApi~jatekosIdSzankciokGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Szankcio>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/JatekosApi~jatekosIdSzankciokGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Szankcio>}
     */
    jatekosIdSzankciokGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling jatekosIdSzankciokGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [Szankcio];
      return this.apiClient.callApi(
        '/Jatekos/{id}/szankciok', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the jatekosPost operation.
     * @callback module:api/JatekosApi~jatekosPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Jatekos} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/Jatekos} [jatekos] 
     * @param {module:api/JatekosApi~jatekosPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Jatekos}
     */
    jatekosPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['jatekos'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = Jatekos;
      return this.apiClient.callApi(
        '/Jatekos', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
