/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MlszApi);
  }
}(this, function(expect, MlszApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MlszApi.Gol();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Gol', function() {
    it('should create an instance of Gol', function() {
      // uncomment below and update the code to test Gol
      //var instance = new MlszApi.Gol();
      //expect(instance).to.be.a(MlszApi.Gol);
    });

    it('should have the property golId (base name: "golId")', function() {
      // uncomment below and update the code to test the property golId
      //var instance = new MlszApi.Gol();
      //expect(instance).to.be();
    });

    it('should have the property merkozesId (base name: "merkozesId")', function() {
      // uncomment below and update the code to test the property merkozesId
      //var instance = new MlszApi.Gol();
      //expect(instance).to.be();
    });

    it('should have the property jatekosId (base name: "jatekosId")', function() {
      // uncomment below and update the code to test the property jatekosId
      //var instance = new MlszApi.Gol();
      //expect(instance).to.be();
    });

    it('should have the property asszisztJatekosId (base name: "asszisztJatekosId")', function() {
      // uncomment below and update the code to test the property asszisztJatekosId
      //var instance = new MlszApi.Gol();
      //expect(instance).to.be();
    });

    it('should have the property csapatId (base name: "csapatId")', function() {
      // uncomment below and update the code to test the property csapatId
      //var instance = new MlszApi.Gol();
      //expect(instance).to.be();
    });

    it('should have the property golIdeje (base name: "golIdeje")', function() {
      // uncomment below and update the code to test the property golIdeje
      //var instance = new MlszApi.Gol();
      //expect(instance).to.be();
    });

    it('should have the property golVideoId (base name: "golVideoId")', function() {
      // uncomment below and update the code to test the property golVideoId
      //var instance = new MlszApi.Gol();
      //expect(instance).to.be();
    });

  });

}));
