/**
 * MLSZ_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MlszApi);
  }
}(this, function(expect, MlszApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MlszApi.Verseny();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Verseny', function() {
    it('should create an instance of Verseny', function() {
      // uncomment below and update the code to test Verseny
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be.a(MlszApi.Verseny);
    });

    it('should have the property versenyId (base name: "versenyId")', function() {
      // uncomment below and update the code to test the property versenyId
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be();
    });

    it('should have the property liga (base name: "liga")', function() {
      // uncomment below and update the code to test the property liga
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be();
    });

    it('should have the property fordulo (base name: "fordulo")', function() {
      // uncomment below and update the code to test the property fordulo
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be();
    });

    it('should have the property stadionId (base name: "stadionId")', function() {
      // uncomment below and update the code to test the property stadionId
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be();
    });

    it('should have the property kezdesDatum (base name: "kezdesDatum")', function() {
      // uncomment below and update the code to test the property kezdesDatum
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be();
    });

    it('should have the property befejezesDatum (base name: "befejezesDatum")', function() {
      // uncomment below and update the code to test the property befejezesDatum
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be();
    });

    it('should have the property leiras (base name: "leiras")', function() {
      // uncomment below and update the code to test the property leiras
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be();
    });

    it('should have the property aktualis (base name: "aktualis")', function() {
      // uncomment below and update the code to test the property aktualis
      //var instance = new MlszApi.Verseny();
      //expect(instance).to.be();
    });

  });

}));
